/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Structures.Capuccino;
import Structures.DataS;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class FaltantePagoWindow extends javax.swing.JPanel {
    public ArrayList<Capuccino> capuccinoList = DataS.getInstance().cappuccinoList;
    /**
     * Creates new form FaltantePagoWindow
     */
    public FaltantePagoWindow() {
        initComponents();
        showTable();
    }

    
  private void showTable() {
    DefaultTableModel model = (DefaultTableModel) TableContenido.getModel();
    model.setRowCount(0); // Limpiar la tabla
    double totalPagar = 0.0;
    if (!capuccinoList.isEmpty()) {
        for (Capuccino capu : capuccinoList) {
                if (capu.getEstado() == 0) {                        
                        int estado = capu.getEstado();
                        model.addRow(new Object[]{
                            capu.getFecha(),
                            capu.getCapuccinoRealizado(),
                            capu.getCarry(),                            
                            capu.getTotal() ,                            
                            String.format("Q.%.2f", (capu.getTotalPagar())),
                            estado,
                             String.format("Q.%.2f", (capu.getTotalPagar()) + totalPagar),
                        }); 
                        totalPagar += capu.getTotalPagar();
                }
                
        }
     }
      System.out.println("Total a Pagar: " +String.format("Q.%.2f", totalPagar));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableContenido = new javax.swing.JTable();

        TableContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Default", "Default", "Default", "Default", "Q.0.00", "Default", null}
            },
            new String [] {
                "Fecha", "Realizados", "Carry", "Total Realizados", "Total a Pagar", "Estado", "Pago acumulado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableContenido.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(TableContenido);

        scrollPane1.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableContenido;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
